micronaut:
  application:
    name: demoUser
datasources:
  default:
    url: 'jdbc:mysql://localhost:3306/test?useSSl=false&serverTimezone=UTC'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'root'
    schema-generate: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jpa:
  default:
    entity-scan:
      packages:
      - 'com.salman'
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true
        application:
          max: 50
